version: '3'
services:
  app:
    container_name: full_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 4747:4747 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres          
    networks:
      - fullstack

  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/docker/basedata
    networks:
      - fullstack

volumes:
  api:
  database_postgres:                  

networks:
  fullstack:
    driver: bridge
    